# Installing plugins manager
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

# Plugins management
plug "kak-lsp/kak-lsp" do %{
    cargo install --locked --force --path .
} config %{
    hook global WinSetOption filetype=rust %{
        lsp-enable-window
        lsp-inlay-diagnostics-enable buffer
        hook window BufWritePre .* lsp-formatting-sync
        hook window -group rust-inlay-hints BufReload .* rust-analyzer-inlay-hints
        hook window -group rust-inlay-hints NormalIdle .* rust-analyzer-inlay-hints
        hook window -group rust-inlay-hints InsertIdle .* rust-analyzer-inlay-hints
        hook -once -always window WinSetOption filetype=.* %{
            remove-hooks window rust-inlay-hints
        }
    }
}
plug "alexherbo2/auto-pairs.kak" config %{
    enable-auto-pairs
}
plug "andreyorst/smarttab.kak" defer smarttab %{
    # when `backspace' is pressed, 4 spaces are deleted at once
    set-option global softtabstop 4
} config %{
    # these languages will use `expandtab' behavior
    hook global WinSetOption filetype=(rust|markdown|kak|lisp|scheme|sh|perl|org) expandtab
    # these languages will use `noexpandtab' behavior
    hook global WinSetOption filetype=(makefile) noexpandtab
    # these languages will use `smarttab' behavior
    hook global WinSetOption filetype=(c|cpp) smarttab
}
plug "andreyorst/powerline.kak" defer powerline_palenight %{
    powerline-format global 'git bufname filetype mode_info line_column position'
    powerline-theme palenight
} config %{
    powerline-start
}
plug "andreyorst/fzf.kak"
plug "danr/kakoune-easymotion"
plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}
plug "andreyorst/kaktree" config %{
    hook global WinSetOption filetype=kaktree %{
        remove-highlighter buffer/numbers
        remove-highlighter buffer/matching
        remove-highlighter buffer/wrap
        remove-highlighter buffer/show-whitespaces
    }
    kaktree-enable
}

colorscheme palenight
add-highlighter global/ number-lines

# Move prev word with ctrl+<-
map global normal <c-left> 'b;'
map global insert <c-left> '<esc>b;i'
# Move next word with ctrl+->
map global normal <c-right> 'e;'
map global insert <c-right> '<esc>e;i'
# Del prev word with ctrl+backspace
map global insert <c-backspace> '<esc>bdi'
# Del next word with ctrl+del
map global insert <c-del> '<esc>edi'

hook global WinCreate .* %{
    hook window InsertCompletionShow .* %{
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }

    hook window InsertCompletionHide .* %{
        unmap window insert <tab> <c-n>
        unmap window insert <s-tab> <c-p>
    }
}
