[nix]
image="archlinux:latest"
additional_packages="bash-completion kitty-terminfo vim zsh-autocomplete git"
unshare_all=true
escape_selinux=false
unconfined=false
# If init=true isolate from host running user so no gui apps
init=true
home="~/DistroHome/Nix"
volume="~/DistroHome/.nix:/nix ~/DistroHome/DevNonCritical:/home/astrid/DistroHome/DevNonCritical ~/DistroHome/DevVoid:/home/astrid/DistroHome/DevVoid"
init_hooks="[ -f /nix/nix-installer ] && /nix/nix-installer uninstall --no-confirm;"
init_hooks="curl -fsSL https://install.determinate.systems/nix | sh -s -- install --no-confirm --prefer-upstream-nix;"
init_hooks="nix-channel --add https://nixos.org/channels/nixos-25.11 nixos && nix-channel --update;"
init_hooks="nix profile add nixpkgs#nixos-rebuild;"
exported_bins="/nix/var/nix/profiles/default/bin/nix /nix/var/nix/profiles/default/bin/nix-collect-garbage /nix/var/nix/profiles/default/bin/nix-build /home/astrid/.nix-profile/bin/nixos-rebuild"
