[noncritical-dev]
image="archlinux:latest"
additional_packages="base-devel bash-completion difftastic emacs eza fzf git just kitty-terminfo lazygit marksman mergiraf mise opentofu ripgrep shellcheck starship vim zed zoxide zsh-autocomplete"
unshare_devsys=true
unshare_groups=true
unshare_ipc=true
# Share Host network
unshare_netns=false
unshare_process=true
unshare_home=true
unshare_root=true
unshare_appdirs=true
unshare_journal=true
# Required for gui apps (like zed)
escape_selinux=true
home="~/DistroHome/DevNonCritical"
volume="~/DistroHome/.shared/rustup:/home/astrid/.rustup ~/DistroHome/.shared/cargo:/home/astrid/.cargo ~/DistroHome/.shared/mise:/home/astrid/.local/share/mise ~/DistroHome/.shared/doom:/home/astrid/.config/doom"
