[random-soft]
image="archlinux:latest"
additional_packages="bash-completion eza fzf git kitty-terminfo mise vim zoxide zsh-autocomplete"
# Required for DRM device to work
unshare_devsys=false
unshare_groups=true
unshare_ipc=true
# Share Host network
unshare_netns=false
unshare_process=true
unshare_home=true
unshare_root=true
unshare_appdirs=true
unshare_journal=true
# Required for gui apps (like zed)
escape_selinux=true
home="~/DistroHome/RandomSoft"
volume="~/DistroHome/.shared/mise:/home/astrid/.local/share/mise"
