[random-soft]
image="archlinux:latest"
additional_packages="bash-completion eza fzf git kitty-terminfo mise vim zoxide zsh-autocomplete"
unshare_all=true
escape_selinux=true
# If init=true isolate from host running user so no gui apps
init=false
home="~/DistroHome/RandomSoft"
