[template]
image="archlinux:latest"
additional_packages="base-devel bash-completion difftastic emacs eza fd fzf git hunspell hunspell-en_us hunspell-fr jdk21-openjdk just kitty-terminfo marksman mergiraf mise noto-fonts-emoji pkgconf ripgrep shellcheck starship vim zoxide zsh-autocomplete"
unshare_devsys=true
unshare_groups=true
unshare_ipc=true
# Share Host network
unshare_netns=false
unshare_process=true
# Required to be disabled for overlay_home
unshare_home=false
unshare_appdirs=true
unshare_journal=true
unshare_root=true
# Required for gui apps (like emacs)
escape_selinux=true
unconfined=false
# If init=true isolate from host running user so no gui apps
init=false
# Overlay Template home
home="~/DistroHome/Template"
# Home is based on Template dir but its only writable in a temporary overlay
#overlay_home=true
volume="~/DistroHome/.shared/doom:/home/astrid/.config/doom:ro ~/DistroHome/.shared/enchant-dic:/home/astrid/.config/enchant:ro"
