[template]
image="archlinux:latest"
additional_packages="bash-completion difftastic eza fzf fd git just kitty-terminfo mergiraf mise ripgrep shellcheck starship vim zed zoxide zsh-autocomplete"
unshare_devsys=true
unshare_groups=true
unshare_ipc=true
unshare_netns=true
unshare_process=true
# Required to be disabled for overlay_home
unshare_home=false
unshare_appdirs=true
unshare_journal=true
unshare_root=true
# Required for gui apps (like zed)
escape_selinux=true
unconfined=false
# If init=true isolate from host running user so no gui apps
init=false
# Overlay Template home
home="~/DistroHome/Template"
# Home is based on Template dir but its only writable in a temporary overlay
overlay_home=true
