[void-dev]
image="archlinux:latest"
additional_packages="base-devel bash-completion difftastic emacs eza fd fzf git go-yq just kitty-terminfo lazygit marksman mergiraf mise neovim noto-fonts-emoji opentofu ripgrep shellcheck starship vim zed zola zoxide zsh-autocomplete vscode-html-languageserver vscode-css-languageserver vscode-json-languageserver typescript-language-server"
# Required for embedded devices projects to work
unshare_devsys=false
unshare_groups=true
unshare_ipc=true
# Share Host network
unshare_netns=false
unshare_process=true
unshare_home=true
unshare_root=true
unshare_appdirs=true
unshare_journal=true
# Required for gui apps (like zed)
escape_selinux=true
home="~/DistroHome/DevVoid"
volume="~/DistroHome/.shared/rustup:/home/astrid/.rustup ~/DistroHome/.shared/cargo:/home/astrid/.cargo ~/DistroHome/.shared/mise:/home/astrid/.local/share/mise ~/DistroHome/.shared/doom:/home/astrid/.config/doom"

